include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/*.g.dart"

linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true
